{% set name = "katex" %}
{% set version = "0.16.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/KaTeX/KaTeX/archive/refs/tags/v{{ version }}.tar.gz
    sha256: dc6b79cc67c479111e99b3ac564387f21f09ac6fb30379770c13dc7ad9f088f5

  - url: https://github.com/KaTeX/KaTeX/releases/download/v{{ version }}/katex.tar.gz
    sha256: 9fbc39989ed20d0e3fb3ea411b5f7657203fd78df4ef3a6383c867d703e350cf
    folder: dist

build:
  number: 0
  noarch: generic
  script:
    - tgz=$(npm pack)
    - npm install -g $tgz

requirements:
  host:
    - nodejs
  run:
    - nodejs
    - __unix

test:
  commands:
    - test -f $PREFIX/bin/katex
    - katex --version

about:
  home: https://github.com/KaTeX/KaTeX
  license: MIT
  license_file: LICENSE
  summary: Fast math typesetting for the web.

extra:
  recipe-maintainers:
    - isuruf
